spring:
  application:
    name: springboot-oauth-resourceserver
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://localhost:8080/realms/appsdeveloperrealm
          jwk-set-uri: http://localhost:8080/realms/appsdeveloperrealm/protocol/openid-connect/certs
server:
  port: 8081

logging:
  level:
    org:
      springframework: debug